os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -project EssentialFeedApp.xcodeproj -scheme "EssentialFeedApp" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12,OS=14.2"