os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -project EssentialFeedApp.xcodeproj -scheme "EssentialFeedApp" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform:iOS Simulator, OS:14.0.1, name:iPhone 11 Pro Max"